human_prompt = """ You have to provide a legal business idea. You business idea should be related to sport. 
Your busines idea will be rephrased by a virtual agent. If the rephrased business idea is OK for you you must return {{terminated}}.
You are allowed to suggest modifications otherwise
-----
- VirtualCorp message: <MESSAGE>
- your last message: <LAST MESSAGE>
-----
"""

agent_prompt="""You will be provided by a message from another agent. You role is to rephrase a business idea and return back your rephrased version.
The message that you will recieve can be either the business idea or a comment on your previous answer. In this case you will be provided also with you last answer
-----
Message of the agent: <MESSAGE>
your last rephrased business idea: <LAST MESSAGE>
-----
Your answer must be only with your rephrased business idea.
If the message containes {{terminated}} you must return your last business idea and nothing else.
"""
extract_rules_template="""You will be provided with the prompt of two agents. Agent 1 is named <FIRST AGENT NAME>. Agent 2 is named <SECOND AGENT NAME>.
Each agent recieved a set of instructions. You role is to extract from these instructions and only from these instructions
the constrains that apply to the agent: <EXTRACT RULES FOR AGENT>. Don't invent rules that are not mentioned in the instructions of the agents.
 ------------------------------------
 First agent instructions are: <FIRST AGENT INSTRUCTIONS>
 ------------------------------------
 Second agent instructions are: <SECOND AGENT INSTRUCTIONS>
 ------------------------------------
Your answer should be limited to the rules and constrains that agent <EXTRACT RULES FOR AGENT> must comply with for his answer to be compliant 
Ignore any rule related to termination condition
Return your answer as a bullet list of rules. DO not add anythink else to your answer:
"""

extract_termination_keywords="""You will be provided with the the instructions of two agents. Agent 1 is named <FIRST AGENT NAME>. Agent 2 is named <SECOND AGENT NAME>.
Each agent recieved a set of instructions. They will collaborate to achieve a mission. The mission ends once on of the agents return a termination keyword. 
You role is to extract this termination keyword from the instructions that each agent recieved.
 ------------------------------------
 Agent1 instructions: <FIRST AGENT INSTRUCTIONS>
 ------------------------------------
  ------------------------------------
 Agent2 instructions: <SECOND AGENT INSTRUCTIONS>
 ------------------------------------
Your answer should contain only the termination keywords
Return your answer as a bullet list of keywords. DO not add anythink else to your answer:
"""

compliance_check_prompt = """ You will be provided with a message generated by an agent and a set of compliance rules.
Your role is to check if the message is compliant with the provided rules.
Your answer should be either "COMPLIANT" or "NON COMPLIANT". If the message is non compliant you must provide 
a step by step and very detailed explanation of the reasons of the non compliance and suggets how to make the message compliant.
Refer only to the provided rules.
---------
Sender Agent name: <AGENT NAME>
Sent message: <MESSAGE>
Compliance rules: <RULES>
-----
If the agent message is compliant with hte rule you must answer only with the word: COMPLIANT and nothing else
"""

